[app]
description = "TV streaming server and recorder"
helptext = "{{|App|}}TVheadend{{[-]}} works as a proxy server: is a TV streaming server and recorder for Linux, FreeBSD and Android supporting DVB-S, DVB-S2, DVB-C, DVB-T, ATSC, ISDB-T, IPTV, SAT>IP and HDHomeRun as input sources. {{|App|}}Tvheadend{{[-]}} offers the HTTP (VLC, MPlayer), HTSP (Kodi, Movian) and SAT>IP streaming. Multiple EPG sources are supported (over-the-air DVB and ATSC including OpenTV DVB extensions, XMLTV, PyXML)."
website = "https://www.tvheadend.org/"

["tvheadend<__instance>:RUN_OPTS"]
helpline = "Additional command-line options passed to TVheadend on startup."
