["codeserver:PASSWORD"]
helpline = "Password to access the code-server web UI."

["codeserver:SUDO_PASSWORD"]
helpline = "Password for sudo access inside the code-server terminal. Leave blank to disable sudo."
