[app]
description = "{{|App|}}VS Code{{[-]}} running on a remote server, accessible through the browser"
helptext = "{{|App|}}Code-server{{[-]}} is VS Code running on a remote server, accessible through the browser."
website = "https://coder.com/"

["codeserver<__instance>:PASSWORD"]
helpline = "Password to access the code-server web UI."

["codeserver<__instance>:SUDO_PASSWORD"]
helpline = "Password for sudo access inside the code-server terminal. Leave blank to disable sudo."
