[app]
description = "Web radio management suite with Liquidsoap and Icecast."
helptext = "{{|App|}}AzuraCast{{[-]}} is a free and open-source self-hosted web radio management suite that includes the full suite of software needed to build, manage and broadcast a web radio station. Out of the box, it includes a rich web interface, an AutoDJ powered by {{|App|}}Liquidsoap{{[-]}}, and {{|App|}}Icecast{{[-]}} to serve broadcasts to listeners."
website = "https://azuracast.com/"

["azuracast<__instance>:APPLICATION_ENV"]
helpline = "Application environment mode."

[["azuracast<__instance>:APPLICATION_ENV".options]]
value = "'production'"
label = "Production"
help = "Optimised for live use (recommended)."

[["azuracast<__instance>:APPLICATION_ENV".options]]
value = "'development'"
label = "Development"
help = "Verbose errors and debug tools enabled."

["azuracast<__instance>:ENABLE_REDIS"]
helpline = "Enable Redis for session and cache storage (recommended)."

[["azuracast<__instance>:ENABLE_REDIS".options]]
value = "'true'"
label = "Enabled"

[["azuracast<__instance>:ENABLE_REDIS".options]]
value = "'false'"
label = "Disabled"

["azuracast<__instance>:MYSQL_HOST"]
helpline = "MySQL/MariaDB hostname."

["azuracast<__instance>:MYSQL_DATABASE"]
helpline = "Database name for AzuraCast."

["azuracast<__instance>:MYSQL_USER"]
helpline = "Database username."

["azuracast<__instance>:MYSQL_PASSWORD"]
helpline = "Database password."
