[app]
description = "Secure network tunneling VPN"
helptext = "{{|App|}}OpenVPN-AS{{[-]}} is a full featured secure network tunneling VPN software solution that integrates {{|App|}}OpenVPN{{[-]}} server capabilities, enterprise management capabilities, simplified {{|App|}}OpenVPN{{[-]}} Connect UI, and {{|App|}}OpenVPN{{[-]}} Client software packages that accommodate Windows, MAC, Linux, Android, and iOS environments. {{|App|}}OpenVPN Access Server{{[-]}} supports a wide range of configurations, including secure and granular remote access to internal network and/ or private cloud network resources and applications with fine-grained access control."
website = "https://openvpn.net/index.php/access-server/overview.html"

["openvpnas<__instance>:INTERFACE"]
helpline = "Network interface the OpenVPN Access Server binds to."

[["openvpnas<__instance>:INTERFACE".options]]
value = "'eth0'"
label = "eth0"
help = "Default ethernet interface."

[["openvpnas<__instance>:INTERFACE".options]]
value = "'eth1'"
label = "eth1"

[["openvpnas<__instance>:INTERFACE".options]]
value = "'ens3'"
label = "ens3"
help = "Common interface name on cloud/virtual machines."
