services:
  unifinetworkapplication<__instance>:
    ports:
      - ${UNIFINETWORKAPPLICATION<__INSTANCE>__PORT_1900?}:1900/udp
      - ${UNIFINETWORKAPPLICATION<__INSTANCE>__PORT_3478?}:3478/udp
      - ${UNIFINETWORKAPPLICATION<__INSTANCE>__PORT_5514?}:5514/udp
      - ${UNIFINETWORKAPPLICATION<__INSTANCE>__PORT_6789?}:6789
      - ${UNIFINETWORKAPPLICATION<__INSTANCE>__PORT_8080?}:${UNIFINETWORKAPPLICATION<__INSTANCE>__PORT_8080?}
      - ${UNIFINETWORKAPPLICATION<__INSTANCE>__PORT_8443?}:8443
      - ${UNIFINETWORKAPPLICATION<__INSTANCE>__PORT_8843?}:8843
      - ${UNIFINETWORKAPPLICATION<__INSTANCE>__PORT_8880?}:8880
      - ${UNIFINETWORKAPPLICATION<__INSTANCE>__PORT_10001?}:10001/udp
