[app]
description = "(DEPRECATED) No replacement"
helptext = "{{|App|}}Samba{{[-]}} is using the `SMB` protocol to share Linux mounts, which then are accessible and mountable on a Windows computer. By default, {{|App|}}Samba{{[-]}} will share all media directories and Docker config directory over SMB on the host. All of these directories will be placed inside whatever share name is specified for `SAMBA__ENVIRONMENT_SHARENAME` in your `.env` file. These shares are protected with username `ds` and password `ds` by default, but **can and should be** changed in your `.env` file."
website = "https://www.samba.org/"

["samba<__instance>:WORKGROUP"]
helpline = "SMB workgroup name (typically WORKGROUP for home networks)."

["samba<__instance>:NMBD"]
helpline = "Run the NetBIOS name service daemon for network discovery."

[["samba<__instance>:NMBD".options]]
value = "'true'"
label = "Enabled"
help = "Allows the share to appear in network browsers."

[["samba<__instance>:NMBD".options]]
value = "'false'"
label = "Disabled"
