["recyclarr<__instance>:RECYCLARR_CREATE_CONFIG"]
helpline = "Generate a starter recyclarr.yml config file on first run."

[["recyclarr<__instance>:RECYCLARR_CREATE_CONFIG".options]]
value = "'true'"
label = "Enabled"
help = "Create a default config file if none exists (recommended for first run)."

[["recyclarr<__instance>:RECYCLARR_CREATE_CONFIG".options]]
value = "'false'"
label = "Disabled"
