[app]
description = "Docker image based off of Ubuntu:18.04 for TP-Link {{|App|}}Omada Controller{{[-]}} to control TP-Link Omada EAP Series Wireless Access Points"
helptext = "Docker image based off of Ubuntu 18.04 for TP-Link Omada Controller to control TP-Link Omada EAP Series Wireless Access Points."
website = "https://www.tp-link.com/en/products/details/EAP-Controller.html"

["omadacontroller<__instance>:SHOW_SERVER_LOGS"]
helpline = "Stream Omada server logs to the container output."

[["omadacontroller<__instance>:SHOW_SERVER_LOGS".options]]
value = "'true'"
label = "Enabled"

[["omadacontroller<__instance>:SHOW_SERVER_LOGS".options]]
value = "'false'"
label = "Disabled"

["omadacontroller<__instance>:SHOW_MONGODB_LOGS"]
helpline = "Stream MongoDB logs to the container output (very verbose)."

[["omadacontroller<__instance>:SHOW_MONGODB_LOGS".options]]
value = "'false'"
label = "Disabled"

[["omadacontroller<__instance>:SHOW_MONGODB_LOGS".options]]
value = "'true'"
label = "Enabled"

["omadacontroller<__instance>:SMALL_FILES"]
helpline = "Optimize MongoDB storage for SSDs using smaller file sizes."

[["omadacontroller<__instance>:SMALL_FILES".options]]
value = "'false'"
label = "Disabled"
help = "Standard storage (recommended for HDDs)."

[["omadacontroller<__instance>:SMALL_FILES".options]]
value = "'true'"
label = "Enabled"
help = "Smaller files — better for SSDs."
