["huginn<__instance>:HUGINN_DATABASE_HOST"]
helpline = "Database hostname (e.g. mariadb)."

["huginn<__instance>:HUGINN_DATABASE_NAME"]
helpline = "Database name for Huginn."

["huginn<__instance>:HUGINN_DATABASE_USERNAME"]
helpline = "Database username."

["huginn<__instance>:HUGINN_DATABASE_PASSWORD"]
helpline = "Database password."

["huginn<__instance>:HUGINN_DATABASE_PORT"]
helpline = "Database port (3306 for MySQL/MariaDB)."
