[app]
description = "{{|App|}}Huginn{{[-]}} is a system for building agents that perform automated tasks for you online."
helptext = "{{|App|}}Huginn{{[-]}} is a system for building agents that perform automated tasks for you online. They can read the web, watch for events, and take actions on your behalf. {{|App|}}Huginn{{[-]}}'s Agents create and consume events, propagating them along a directed graph. Think of it as a hackable version of IFTTT or Zapier on your own server. You always know who has your data. You do."
website = "https://github.com/huginn/huginn"

["huginn<__instance>:HUGINN_DATABASE_HOST"]
helpline = "Database hostname (e.g. mariadb)."

["huginn<__instance>:HUGINN_DATABASE_NAME"]
helpline = "Database name for Huginn."

["huginn<__instance>:HUGINN_DATABASE_USERNAME"]
helpline = "Database username."

["huginn<__instance>:HUGINN_DATABASE_PASSWORD"]
helpline = "Database password."

["huginn<__instance>:HUGINN_DATABASE_PORT"]
helpline = "Database port (3306 for MySQL/MariaDB)."
