["pihole<__instance>:WEBPASSWORD"]
helpline = "Password for the Pi-hole web admin interface."

["pihole<__instance>:ServerIP"]
helpline = "IP address of the server running Pi-hole. Use 0.0.0.0 to bind all interfaces."

["pihole<__instance>:DNS1"]
helpline = "Primary upstream DNS server."

[["pihole<__instance>:DNS1".options]]
value = "'1.1.1.1'"
label = "Cloudflare"

[["pihole<__instance>:DNS1".options]]
value = "'8.8.8.8'"
label = "Google"

[["pihole<__instance>:DNS1".options]]
value = "'9.9.9.9'"
label = "Quad9"

[["pihole<__instance>:DNS1".options]]
value = "'208.67.222.222'"
label = "OpenDNS"

["pihole<__instance>:DNS2"]
helpline = "Secondary upstream DNS server."

[["pihole<__instance>:DNS2".options]]
value = "'1.0.0.1'"
label = "Cloudflare"

[["pihole<__instance>:DNS2".options]]
value = "'8.8.4.4'"
label = "Google"

[["pihole<__instance>:DNS2".options]]
value = "'149.112.112.112'"
label = "Quad9"

[["pihole<__instance>:DNS2".options]]
value = "'208.67.220.220'"
label = "OpenDNS"
