[app]
description = "Cross-platform system monitoring tool"
helptext = "{{|App|}}Glances{{[-]}} is a cross-platform monitoring tool which aims to present a large amount of monitoring information through a curses or Web based interface. The information dynamically adapts depending on the size of the user interface."
website = "https://nicolargo.github.io/glances/"

["glances<__instance>:GLANCES_OPT"]
helpline = "Command-line options passed to Glances."

[["glances<__instance>:GLANCES_OPT".options]]
value = "'-w'"
label = "Web server"
help = "Run the built-in web server (recommended)."

[["glances<__instance>:GLANCES_OPT".options]]
value = "'-w --disable-plugin gpu'"
label = "Web (no GPU)"
help = "Web server with GPU monitoring disabled."
