[app]
description = "VPN client in a thin Docker container for multiple VPN providers."
helptext = "{{|App|}}Gluetun{{[-]}} is a VPN client in a thin Docker container for multiple VPN providers, written in Go, and using {{|App|}}OpenVPN{{[-]}} or {{|App|}}Wireguard{{[-]}}, DNS over TLS, with a few proxy servers built-in."
website = "https://github.com/qdm12/gluetun"

["gluetun<__instance>:VPN_SERVICE_PROVIDER"]
helpline = "Your VPN service provider."
helptext = "The VPN provider to use with {{|App|}}Gluetun{{[-]}}. See https://github.com/qdm12/gluetun-wiki for supported providers and required variables for each."

[["gluetun<__instance>:VPN_SERVICE_PROVIDER".options]]
value = "'private internet access'"
label = "Private Internet Access"

[["gluetun<__instance>:VPN_SERVICE_PROVIDER".options]]
value = "'mullvad'"
label = "Mullvad"

[["gluetun<__instance>:VPN_SERVICE_PROVIDER".options]]
value = "'nordvpn'"
label = "NordVPN"

[["gluetun<__instance>:VPN_SERVICE_PROVIDER".options]]
value = "'surfshark'"
label = "Surfshark"

[["gluetun<__instance>:VPN_SERVICE_PROVIDER".options]]
value = "'expressvpn'"
label = "ExpressVPN"

[["gluetun<__instance>:VPN_SERVICE_PROVIDER".options]]
value = "'protonvpn'"
label = "ProtonVPN"

[["gluetun<__instance>:VPN_SERVICE_PROVIDER".options]]
value = "'airvpn'"
label = "AirVPN"

[["gluetun<__instance>:VPN_SERVICE_PROVIDER".options]]
value = "'ipvanish'"
label = "IPVanish"

[["gluetun<__instance>:VPN_SERVICE_PROVIDER".options]]
value = "'cyberghost'"
label = "CyberGhost"

[["gluetun<__instance>:VPN_SERVICE_PROVIDER".options]]
value = "'custom'"
label = "Custom"
help = "Use a custom OpenVPN or WireGuard configuration file."

["gluetun<__instance>:VPN_TYPE"]
helpline = "VPN protocol to use."

[["gluetun<__instance>:VPN_TYPE".options]]
value = "'openvpn'"
label = "OpenVPN"

[["gluetun<__instance>:VPN_TYPE".options]]
value = "'wireguard'"
label = "WireGuard"

["gluetun<__instance>:OPENVPN_PROTOCOL"]
helpline = "Transport protocol for OpenVPN."

[["gluetun<__instance>:OPENVPN_PROTOCOL".options]]
value = "'udp'"
label = "UDP"
help = "Faster, preferred when available."

[["gluetun<__instance>:OPENVPN_PROTOCOL".options]]
value = "'tcp'"
label = "TCP"
help = "More reliable through restrictive firewalls."
