[app]
description = "A full-featured database management tool"
helptext = "{{|App|}}Adminer{{[-]}} (formerly {{|App|}}phpMinAdmin{{[-]}}) is a full-featured database management tool written in PHP. {{|App|}}Adminer{{[-]}} is available for MySQL, MariaDB, PostgreSQL, SQLite, MS SQL, Oracle, Elasticsearch, MongoDB and others via plugin."
website = "https://www.adminer.org/"

["adminer<__instance>:ADMINER_DESIGN"]
helpline = "The UI theme for Adminer."
helptext = "{{|App|}}Adminer{{[-]}} ships with several built-in design themes. Leave blank for the default theme."

[["adminer<__instance>:ADMINER_DESIGN".options]]
value = "''"
label = "Default"

[["adminer<__instance>:ADMINER_DESIGN".options]]
value = "'brade'"
label = "Brade"

[["adminer<__instance>:ADMINER_DESIGN".options]]
value = "'bueltgen'"
label = "Bueltgen"

[["adminer<__instance>:ADMINER_DESIGN".options]]
value = "'galkaev'"
label = "Galkaev"

[["adminer<__instance>:ADMINER_DESIGN".options]]
value = "'hydra'"
label = "Hydra"

[["adminer<__instance>:ADMINER_DESIGN".options]]
value = "'jukin'"
label = "Jukin"

[["adminer<__instance>:ADMINER_DESIGN".options]]
value = "'lucas-sandery'"
label = "Lucas Sandery"

[["adminer<__instance>:ADMINER_DESIGN".options]]
value = "'mvt'"
label = "MVT"

[["adminer<__instance>:ADMINER_DESIGN".options]]
value = "'ng9'"
label = "ng9"

[["adminer<__instance>:ADMINER_DESIGN".options]]
value = "'pappu687'"
label = "Pappu687"

[["adminer<__instance>:ADMINER_DESIGN".options]]
value = "'pepa-linha'"
label = "Pepa Linha"

[["adminer<__instance>:ADMINER_DESIGN".options]]
value = "'price'"
label = "Price"

[["adminer<__instance>:ADMINER_DESIGN".options]]
value = "'rmsoft'"
label = "RMSoft"

[["adminer<__instance>:ADMINER_DESIGN".options]]
value = "'rmsoft_blue'"
label = "RMSoft Blue"

[["adminer<__instance>:ADMINER_DESIGN".options]]
value = "'selenity'"
label = "Selenity"

[["adminer<__instance>:ADMINER_DESIGN".options]]
value = "'simpleui'"
label = "SimpleUI"

["adminer<__instance>:ADMINER_PLUGINS"]
helpline = "Space-separated list of Adminer plugins to enable."
helptext = "Plugins extend {{|App|}}Adminer{{[-]}}'s functionality. Separate multiple plugin names with a space."
