["postgres<__instance>:POSTGRES_PASSWORD"]
helpline = "Password for the PostgreSQL superuser. Required on first startup."

["postgres<__instance>:POSTGRES_USER"]
helpline = "Username for the PostgreSQL superuser."
