[app]
description = "Use Amazon Dash buttons to communicate with {{|App|}}Home Assistant{{[-]}}."
helptext = "{{|App|}}Dasshio{{[-]}} is a Hass.io add-on to easily use Amazon Dash Buttons with {{|App|}}Home Assistant{{[-]}}."
website = "https://github.com/danimtb/dasshio"

["dasshio<__instance>:HA_BASE_URL"]
helpline = "Base URL of your Home Assistant instance (e.g. http://homeassistant:8123)."

["dasshio<__instance>:HASSIO_TOKEN"]
helpline = "Long-lived access token from your Home Assistant profile page."
