services:
  paperlessngx<__instance>:
    image: ghcr.io/paperless-ngx/paperless-ngx:${PAPERLESSNGX<__INSTANCE>__TAG?}
  paperlessngx<__instance>-postgres:
    image: docker.io/library/postgres:${PAPERLESSNGX<__INSTANCE>__POSTGRES_TAG?}
  paperlessngx<__instance>-redis:
    image: docker.io/library/redis:${PAPERLESSNGX<__INSTANCE>__REDIS_TAG?}
