["immich<__instance>:DB_PASSWORD"]
helpline = "PostgreSQL database password."

["immich<__instance>:DB_USERNAME"]
helpline = "PostgreSQL database username."

["immich<__instance>:DB_DATABASE_NAME"]
helpline = "PostgreSQL database name."

["immich<__instance>:DB_HOSTNAME"]
helpline = "PostgreSQL hostname (set automatically to the companion postgres container)."

["immich<__instance>:REDIS_HOSTNAME"]
helpline = "Redis hostname (set automatically to the companion redis container)."
