["immich:DB_PASSWORD"]
helpline = "PostgreSQL database password."

["immich:DB_USERNAME"]
helpline = "PostgreSQL database username."

["immich:DB_DATABASE_NAME"]
helpline = "PostgreSQL database name."

["immich:DB_HOSTNAME"]
helpline = "PostgreSQL hostname (set automatically to the companion postgres container)."

["immich:REDIS_HOSTNAME"]
helpline = "Redis hostname (set automatically to the companion redis container)."
