[app]
description = "A self-hosted startpage for your server. Easily manage your apps and bookmarks with built-in editors."
helptext = "{{|App|}}Flame{{[-]}} is self-hosted startpage for your server. Its design is inspired (heavily) by SUI. {{|App|}}Flame{{[-]}} is very easy to setup and use. With built-in editors, it allows you to setup your very own application hub in no time - no file editing necessary."
website = "https://github.com/pawelmalak/flame"

["flame<__instance>:PASSWORD"]
helpline = "Password to access the Flame settings panel. Leave blank to disable password protection."
