["portaineragent<__instance>:CAP_HOST_MANAGEMENT"]
helpline = "Allow Portainer Agent to manage host-level resources."

[["portaineragent<__instance>:CAP_HOST_MANAGEMENT".options]]
value = "'1'"
label = "Enabled"
help = "Required for full host management from Portainer."

[["portaineragent<__instance>:CAP_HOST_MANAGEMENT".options]]
value = "'0'"
label = "Disabled"
