["youtubedl:YDL_DEBUG"]
helpline = "Enable verbose debug logging."

[["youtubedl:YDL_DEBUG".options]]
value = "'false'"
label = "Disabled"

[["youtubedl:YDL_DEBUG".options]]
value = "'true'"
label = "Enabled"

["youtubedl:YDL_CONFIG_PATH"]
helpline = "Path to the yt-dlp/youtube-dl config file inside the container."
