name: Trigger Site Build
on:
  workflow_run:
    workflows: ["Validate"]
    types:
      - completed
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build in main repo
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3
        with:
          token: ${{ secrets.GH_PAT_TRIGGER_BUILD }}
          repository: GhostWriters/DockSTARTer-Docs
          event-type: templates-update
